Repository nimblehq/android-common-ktx, pull requests merged in 2021-11, with the labels that each got.

#13 [12] Setup .github template and README
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/story_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  README.md
Labels: type : chore

#23 [#6] [Feature] As a developer, I want to use the TypedArray Extension
  common-ktx/src/main/java/co/nimblehq/common/extensions/TypedArrayExt.kt
Labels: type : feature

#18 [chore] Add .idea/misc.xml to .gitignore
  .gitignore
Labels: type : chore

#19 [chore] Add code owner for automatically require review
  .github/CODEOWNERS
Labels: type : chore

#16 [#8] Add Set/Get/ClearAll for SharedPreferences extension
  common-ktx/build.gradle
  common-ktx/src/androidTest/java/co/nimblehq/common/extensions/SharedPreferencesExtTest.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/SharedPreferencesExt.kt
Labels: type : feature, priority: must-have

#14 [#10] [Feature] As a developer, I want to use the Context Extension
  common-ktx/src/main/java/co/nimblehq/common/extensions/ContextExt.kt
Labels: type : feature

#26 [#4] Add string extensions
  common-ktx/src/main/java/co/nimblehq/common/extensions/StringExt.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/StringExtTest.kt
Labels: type : feature

#15 [#9] [Feature] As a developer, I want to use the Activity Extension
  common-ktx/src/main/java/co/nimblehq/common/extensions/ActivityExt.kt
Labels: type : feature

#17 [#2] Add View Extension
  common-ktx/src/main/java/co/nimblehq/common/extensions/ViewExt.kt
Labels: type : feature

#24 [#6] As a developer, I want to use the TypedArray Extension
  common-ktx/src/main/java/co/nimblehq/common/extensions/TypedArrayExt.kt
Labels: type : feature

#30 [#7] [Feature] As a developer, I want to use the DateExtension
  common-ktx/src/main/java/co/nimblehq/common/extensions/DateExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/IntExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/TypedArrayExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/date/DateRange.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/date/TimeInterval.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/DateExtTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/DateRangeTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/IntExtTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/TimeIntervalTest.kt
Labels: type : feature

#28 [#11] Add TextViewExt
  common-ktx/src/main/java/co/nimblehq/common/extensions/TextViewExt.kt
Labels: type : feature

#29 [#22] [Chore] As a developer, I can publish new version on Jitpack once merge release PR
  .github/workflows/release.yml
  common-ktx/build.gradle
  jitpack.yml
  version.properties
Labels: type : chore

#27 [#3] Add ToastExt
  common-ktx/src/main/java/co/nimblehq/common/extensions/ToastExt.kt
Labels: type : feature

#31 Release - 0.0.1
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/ISSUE_TEMPLATE/story_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/workflows/release.yml
  .gitignore
  README.md
  common-ktx/build.gradle
  common-ktx/src/androidTest/java/co/nimblehq/common/extensions/SharedPreferencesExtTest.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/ActivityExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/ContextExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/DateExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/IntExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/SharedPreferencesExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/StringExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/TextViewExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/ToastExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/TypedArrayExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/ViewExt.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/date/DateRange.kt
  common-ktx/src/main/java/co/nimblehq/common/extensions/date/TimeInterval.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/DateExtTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/DateRangeTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/IntExtTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/StringExtTest.kt
  common-ktx/src/test/java/co/nimblehq/common/extensions/TimeIntervalTest.kt
  jitpack.yml
  version.properties
Labels: type : release

#32 [Bug] Cannot build in Jitpack
  common-ktx/build.gradle
  version.properties
Labels: priority : high, type : bug

#36 Release version 0.0.2
  common-ktx/build.gradle
  version.properties
Labels: priority : high
